apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mongodb-storage","namespace":"blue"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: food-cluster-control-plane
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-08-09T16:39:46Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: mongodb-storage
    namespace: blue
    resourceVersion: "29958"
    uid: 425edd7c-994f-45db-837e-49a690e18a6f
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-425edd7c-994f-45db-837e-49a690e18a6f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
