version: "3.9"

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - food-volume:/data/db
    networks:
      - food-network
    restart: always


  backend:
    image: thabith12/food-backend:v2
    container_name: food-backend-container
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - food-network
    restart: always


  frontend:
    image: thabith12/food-frontend:v2
    container_name: food-frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - food-network
    restart: always


volumes:
  food-volume:


networks:
  food-network:
    driver: bridge