apiVersion: v1
kind: ConfigMap
metadata:
  name: food-config
  namespace: green
data:
  PORT: "4000"
  MONGO_URL: "mongodb://admin:password123@mongodb-service:27017/food-delivery?authSource=admin"
  FRONTEND_URL: "http://13.53.49.223:30080"
