apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.namespace }}

data:

  PORT: "{{ .Values.config.PORT }}"

  MONGO_URL: "{{ .Values.config.MONGO_URL }}"

  FRONTEND_URL: "{{ .Values.config.FRONTEND_URL }}"
