apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.frontend.serviceName }}
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: {{ .Values.frontend.name }}

  ports:
    - protocol: TCP

      port: {{ .Values.frontend.servicePort }}

      targetPort: {{ .Values.frontend.containerPort }}

  type: {{ .Values.frontend.serviceType }}
