apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.serviceName }}
                port:
                  number: {{ .Values.frontend.servicePort }}


          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.servicePort }}
