apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.mongodb.serviceName }}
  namespace: {{ .Values.namespace }}

spec:
  clusterIP: None

  selector:
    app: {{ .Values.mongodb.name }}

  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.servicePort }}
      targetPort: {{ .Values.mongodb.containerPort }}
