apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.mongodb.pvcName }}
  namespace: {{ .Values.namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: {{ .Values.mongodb.storageClass }}

  resources:
    requests:
      storage: 2Gi
