apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  JWT_SECRET: "{{ .Values.secret.JWT_SECRET }}"
  MONGO_USERNAME: "{{ .Values.secret.MONGO_USERNAME }}"
  MONGO_PASSWORD: "{{ .Values.secret.MONGO_PASSWORD }}"
