helm:
  parameters:
  - name: backend.image.repository
    value: thabith12/food-backend
    forcestring: true
  - name: backend.image.tag
    value: v6
    forcestring: true
  - name: frontend.image.repository
    value: thabith12/food-frontend
    forcestring: true
  - name: frontend.image.tag
    value: v6
    forcestring: true
