apiVersion: apps/v1
kind: Deployment

metadata:
  name: food-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: food-backend

  template:
    metadata:
      labels:
        app: food-backend

    spec:
      containers:
        - name: backend

          image: thabith12/food-backend:v3

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4000

          env:
            - name: PORT
              value: "4000"

            - name: MONGO_URL
              value: "mongodb://mongodb-service:27017/food-delivery"

            - name: JWT_SECRET
              value: "your_jwt_secret_key_here"

            - name: SALT
              value: "10"

            - name: STRIPE_SECRET_KEY
              value: "sk_test_your_stripe_secret_key_here"

            - name: FRONTEND_URL
              value: "http://16.171.145.71:30080"

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"
