apiVersion: v1
kind: ConfigMap

metadata:
  name: food-config
  namespace: food-app

data:
  PORT: "4000"
  MONGO_URL: "mongodb://admin:password123@mongodb-service:27017/food-delivery?authSource=admin"
  FRONTEND_URL: "http://16.171.145.71:30080"
