apiVersion: v1
kind: Secret
metadata:
  name: food-secret
  namespace: food-app

type: Opaque

stringData:
  JWT_SECRET: "fooddeliverysecret"
  MONGO_USERNAME: "admin"
  MONGO_PASSWORD: "password123"
